import { Topic } from '../app/models/topic.model';

export let array: Topic[] = [
    new Topic("General", "General Discussion"),
    new Topic("GeneralTwo", "General Discussion"),
    new Topic("GeneralThree", "General Discussion"),
    new Topic("GeneralFour", "General Discussion"),
    new Topic("GeneralFive", "General Discussion"),
    new Topic("GeneralSix", "General Discussion"),
    new Topic("GeneralSeven", "General Discussion"),
    new Topic("GeneralEight", "General Discussion"),
    new Topic("GeneralNine", "General Discussion"),
    new Topic("GeneralTen", "General Discussion"),
    new Topic("TechOne", "Tech Discussion"),
    new Topic("TechTwo", "Tech Discussion"),
    new Topic("TechThree", "Tech Discussion"),
    new Topic("TechFour", "Tech Discussion"),
    new Topic("TechFive", "Tech Discussion"),
    new Topic("TechSix", "Tech Discussion"),
    new Topic("TechSeven", "Tech Discussion"),
    new Topic("TechEight", "Tech Discussion"),
    new Topic("TechNine", "Tech Discussion"),
    new Topic("TechTen", "Tech Discussion"),
    new Topic("AngularOne", "Angular Discussion"),
    new Topic("AngularTwo", "Angular Discussion"),
    new Topic("AngularThree", "Angular Discussion"),
    new Topic("AngularFour", "Angular Discussion"),
    new Topic("AngularFive", "Angular Discussion"),
    new Topic("AngularSix", "Angular Discussion"),
    new Topic("AngularSeven", "Angular Discussion"),
    new Topic("AngularEight", "Angular Discussion"),
    new Topic("AngularNine", "Angular Discussion"),
    new Topic("AngularTen", "Angular Discussion"),

];